### ISSUE TITLE
"gray-matter" not found.

### ISSUE THREAD

**Issue by snollygolly** [albogdano/handlebars-helper-mdpartial#1]
After an NPM install, I tried to use this, but got:

```
module.js:341
    throw err;
    ^

Error: Cannot find module 'gray-matter'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
```

**Comment by albogdano** [comment]
Yeah sorry about this, I have forgotten to pin the the dependencies to a specific version and now they got updated to the latest version and broke the module. It happens often with node.js. I'll try and fix this now.

**Comment by snollygolly** [comment]
No worries man, it happens :)

**Comment by albogdano** [comment]
Try with the new `0.3.2` I've just released. I'm using it for a small project that works with the old Assemble and this unfortunately is not compatible with the new version of Assemble. If you still have problems perhaps you can fork it and modify it a bit. It's really small.

**Comment by snollygolly** [comment]
I actually already implemented an extremely stripped down version of what you had.  I ditched grey matter and went right to marked and then compile.  I'll see later though if yours works.  Thanks!

**Comment by albogdano** [comment]
Cool, do whatever you like with it. Let me know I you need any help.
